language: java
jdk:
  - oraclejdk6
env: DISPLAY=:99.0
env: GRIFFON_OPTS="-XX:MaxPermSize=250m -Xmx768m"
script: ./griffonw -non-interactive -Dgriffon.artifact.force.upgrade=true test-app;./griffonw -non-interactive -Dgriffon.artifact.force.upgrade=true package
after_script:
  - test -f ./dist/jar/jttslite-*-jar.zip
  - test -f ./dist/applet/jttslite-*-applet.zip
  - test -f ./dist/webstart/jttslite-*-webstart.zip
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: /bin/true